# Genome reference sequences
genome_reference:
    hard_masked:
        organism: Mouse
        base_url: ftp://ftp.ensembl.org/pub/release-89/fasta/mus_musculus/dna
        name: GRCm38
        units:
            - Mus_musculus.GRCm38.dna_rm.chromosome.1.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.2.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.3.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.4.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.5.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.6.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.7.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.8.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.9.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.10.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.11.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.12.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.13.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.14.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.15.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.16.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.17.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.18.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.19.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.X.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.Y.fa.gz
            - Mus_musculus.GRCm38.dna_rm.chromosome.MT.fa.gz
    unmasked:
        organism: Mouse
        base_url: ftp://ftp.ensembl.org/pub/release-89/fasta/mus_musculus/dna
        name: GRCm38
        units:
            - Mus_musculus.GRCm38.dna.chromosome.1.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.2.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.3.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.4.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.5.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.6.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.7.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.8.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.9.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.10.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.11.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.12.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.13.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.14.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.15.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.16.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.17.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.18.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.19.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.X.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.Y.fa.gz
            - Mus_musculus.GRCm38.dna.chromosome.MT.fa.gz
