# Snakemake workflow
#
# Author: Maurits Evers (maurits.evers@gmail.com)
# License: MIT
# Original date: 28-04-2020
# Last changed: 01-05-2020


# Config files
configfile: "workflow/config.yaml"


# Include specific rules
include: "rules/download_files.smk"
include: "rules/make_reference.smk"
include: "rules/create_align_rDNA_frags.smk"
include: "rules/postprocessing.smk"
include: "rules/generate_circos_plot.smk"


rule all:
    input:
        expand(
            "04_coverage_tracks/{id}/rDNA_frags_len{len}_step{len}.bw",
            id = ["human/GRCh38", "mouse/GRCm38"],
            len = [100, 500, 1000]),
        expand(
            "05_circos_plots/{id}/circos_rDNA_frags_len{len}_step{len}.{ext}",
            id = ["human/GRCh38", "mouse/GRCm38"],
            len = [100, 500, 1000],
            ext = ["pdf", "png"])
